name: crm_pdks_mobile
description: "Mavi Host CRM Mobile"
publish_to: "none"

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.5.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  geolocator: ^14.0.2
  http: ^1.5.0
  jiffy: ^6.4.3
  latlong2: ^0.9.1
  onesignal_flutter: ^5.3.4
  package_info_plus: ^8.3.0
  platform_device_id_plus: ^1.0.7
  provider: ^6.1.5
  sentry_flutter: ^9.6.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
